import type { Metadata } from 'next';
import type { ReactNode } from 'react';

// Self-hosted, so the first paint of every page does not depend on the network
// reaching fonts.googleapis.com. Generated by `scripts/fetch-fonts.ts`.
import './fonts.css';
import './globals.css';

export const metadata: Metadata = {
  title: 'Creator Wishlist',
  description:
    'Send a creator the gear they actually want. Their address stays private.',
};

/**
 * The design-system type — Cormorant Garamond for display, Lora for body text,
 * Courier Prime for monospace evidence (ledger refs, ciphertext, merchant ids) —
 * is declared in `fonts.css`, not linked from Google.
 */
export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
