/**
 * Vendor the design-system fonts into the repo.
 *
 * Why: the app needs Cormorant Garamond, Lora and Courier Prime. Loading them
 * from `fonts.googleapis.com` puts a **render-blocking stylesheet** in the head of
 * every page, which means the demo's first paint depends on venue wifi reaching
 * Google. Self-hosting keeps the exact same typography and removes the network
 * hop entirely.
 *
 * It runs once. The output is committed: the `.woff2` files in `public/fonts/`
 * and the `@font-face` rules in `src/app/fonts.css`. Re-run it only to change the
 * families or weights.
 *
 *   npx tsx scripts/fetch-fonts.ts
 *
 * Only the `latin` subset is taken. Anything outside it falls back to the
 * platform serif, which is correct behaviour rather than a missing glyph — the
 * `unicode-range` is preserved from Google's own CSS so the browser knows when to
 * do that.
 *
 * Licence: these families are all SIL Open Font Licence 1.1, which permits
 * redistribution. If this ships anywhere real, carry the OFL text alongside them.
 */
import { mkdir, writeFile } from 'node:fs/promises';

/** Exactly the families and weights the design system asks for. */
const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,500;0,600;1,400&family=Lora:ital,wght@0,400;0,500;0,600;1,400&family=Courier+Prime:wght@400;700&display=swap';

/** A modern browser UA, so Google serves woff2 rather than legacy ttf. */
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';

const OUT_DIR = 'public/fonts';
const OUT_CSS = 'src/app/fonts.css';

interface Face {
  subset: string;
  family: string;
  style: string;
  weight: string;
  url: string;
  unicodeRange: string | null;
}

function slug(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, '-');
}

function parseFaces(css: string): Face[] {
  const faces: Face[] = [];
  // Google's CSS annotates each block with the subset in a leading comment,
  // which is the only reliable way to tell latin from latin-ext or cyrillic.
  const pattern = /\/\*\s*([a-z0-9-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g;

  for (const match of css.matchAll(pattern)) {
    const subset = match[1] ?? '';
    const block = match[2] ?? '';

    const family = /font-family:\s*'([^']+)'/.exec(block)?.[1];
    const style = /font-style:\s*([a-z]+)/.exec(block)?.[1] ?? 'normal';
    const weight = /font-weight:\s*(\d+)/.exec(block)?.[1] ?? '400';
    const url = /url\((https:\/\/[^)]+\.woff2)\)/.exec(block)?.[1];
    const unicodeRange = /unicode-range:\s*([^;]+);/.exec(block)?.[1] ?? null;

    if (family && url) faces.push({ subset, family, style, weight, url, unicodeRange });
  }

  return faces;
}

console.log('fetching the font CSS...');
const response = await fetch(CSS_URL, { headers: { 'User-Agent': UA } });

if (!response.ok) {
  console.error(`Google Fonts returned HTTP ${response.status}. Nothing changed.`);
  process.exit(1);
}

const css = await response.text();
const faces = parseFaces(css).filter((face) => face.subset === 'latin');

if (faces.length === 0) {
  console.error('No latin @font-face blocks found. Did the CSS shape change?');
  process.exit(1);
}

console.log(`found ${faces.length} latin face(s)`);
await mkdir(OUT_DIR, { recursive: true });

const rules: string[] = [];
let bytes = 0;

for (const face of faces) {
  const file = `${slug(face.family)}-${face.weight}${face.style === 'italic' ? '-italic' : ''}.woff2`;

  const binary = await fetch(face.url, { headers: { 'User-Agent': UA } });
  if (!binary.ok) {
    console.error(`  FAILED ${file}: HTTP ${binary.status}`);
    process.exit(1);
  }

  const buffer = Buffer.from(await binary.arrayBuffer());
  await writeFile(`${OUT_DIR}/${file}`, buffer);
  bytes += buffer.byteLength;

  console.log(`  ${file.padEnd(38)} ${String(Math.round(buffer.byteLength / 1024)).padStart(4)} KB`);

  rules.push(
    [
      '@font-face {',
      `  font-family: '${face.family}';`,
      `  font-style: ${face.style};`,
      `  font-weight: ${face.weight};`,
      '  font-display: swap;',
      `  src: url('/fonts/${file}') format('woff2');`,
      ...(face.unicodeRange ? [`  unicode-range: ${face.unicodeRange};`] : []),
      '}',
    ].join('\n'),
  );
}

const header = [
  '/*',
  ' * Design-system fonts, self-hosted.',
  ' *',
  ' * Generated by `npx tsx scripts/fetch-fonts.ts` — do not hand-edit the',
  ' * @font-face blocks, re-run the script instead.',
  ' *',
  ' * Self-hosted on purpose: a stylesheet link to fonts.googleapis.com is',
  ' * render-blocking, so the first paint of every page would depend on the',
  ' * network reaching Google. The files below are byte-identical to what',
  ' * Google serves; only the URLs changed.',
  ' *',
  ' * SIL Open Font Licence 1.1 — redistribution is permitted.',
  ' */',
  '',
].join('\n');

await writeFile(OUT_CSS, header + rules.join('\n\n') + '\n');

console.log('');
console.log(`wrote ${OUT_CSS}`);
console.log(`${faces.length} face(s), ${Math.round(bytes / 1024)} KB total`);
console.log('');
console.log('Next: remove the <link> tags from src/app/layout.tsx and import this');
console.log("file with `import './fonts.css';` before globals.css.");
